services:
  postgres:
    image: postgres:15-alpine
    container_name: esty-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment: 
      POSTGRES_DB: etsybot
      POSTGRES_USER: etsyuser
      POSTGRES_PASSWORD: etS_yP@ss
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: etsy-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "6379:6379"

  bot:
    build: .
    container_name: etsy-bot
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: python3 -m bot.bot

  poller:
    build: .
    container_name: etsy-poller
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: python3 -m poller.poller

volumes:
  pgdata:
